### ISSUE TITLE
Scroll suddenly stops working

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-tool#1189]
Re-produce bug:

1) Open Entity Picker (click select)
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1190419/168144466-d9811153-df3c-488c-8ab2-f65c562d9f86.png">

2) Close CustomScrim (modal)

It seems that the CusomScrim adds overflow:hidden to body. This is not removed when closing the modal.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1190419/168144366-df0d2476-deed-4475-ba04-abe40a4a2adf.png">

**Comment by soofstad** [comment]
closed by https://github.com/equinor/data-modelling-tool/commit/f351a0842f9c8e46e003add3a57b36af7226651f
