### ISSUE TITLE
on a newly created analysis: fails to fetch AzureContainer blueprint when creating new analysis (see screenshot)

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/data-modelling-tool#1207]
![image](https://user-images.githubusercontent.com/69512295/169993045-9aa0a16b-40f3-458f-91ec-646bf67b6944.png)

**Comment by soofstad** [comment]
I'm unable to recreate this. Does it still exist?

**Comment by KristianKjerstad** [comment]
@soofstad seems to be working again now
