### ISSUE TITLE
Input filed for "input entity" on analysis details pae should be disabled if no entity is selected or created

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/data-modelling-tool#1221]
![image](https://user-images.githubusercontent.com/69512295/171106666-e0159dec-c7c5-435e-b81c-aa69f0ee51dc.png)

**Comment by soofstad** [comment]
closed with; https://github.com/equinor/data-modelling-tool/commit/e22d77750597063a8171a6925271a46ce7ac8c82
