### ISSUE TITLE
image of the runner in the CI has the wrong format. See github action logs in the dmt-mooring-analysis repo

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-tool#1258]

**Comment by netr0m** [comment]
I suppose you're referring to e.g. [build-test-export run](https://github.com/equinor/dmt-mooring-analysis/runs/6915015518?check_suite_focus=true)?

Under `Print ENVIRONMENT`:
```
Run echo "$IMAGE_REGISTRY"
dmtregistry.azurecr.io
dmtregistry.azurecr.io/sima-runtime:latest
```

Under `Pull SIMA DMT`, it seems to successfully pull the image:
```
Run docker pull $SIMA_IMAGE
latest: Pulling from sima-runtime
[...]
Status: Downloaded newer image for dmtregistry.azurecr.io/sima-runtime:latest
dmtregistry.azurecr.io/sima-runtime:latest
```

I was unable to find the `dmtregistry` registry in any of "our" Azure subscriptions, but perhaps this is controlled by Sintef? I was able to find the following registries:
- S398-DataModellingTool:
  - datamodelingtool[.azurecr.io]
  - mariner[.azurecr.io]
  - publicMSA[.azurecr.io]
- S059-Marine-technology-analysis-solutions
  - No registries

I initially thought you were referring to `dmtregistry.azurecr.io/sima-runtime:latest`,
where there should be a "repository" in between `dmtregistry.azurecr.io/` and `sima-runtime:latest`; e.g. `dmtregistry.azurecr.io/some_repo/sima-runtime:latest`, but seeing as it seems to successfully pull the image from the given URL I doubt that's it?
