### ISSUE TITLE
Add support for assets

### ISSUE THREAD

**Issue by netr0m** [equinor/data-modelling-tool#1342]
Currently, the overview page contains a list of analyses. There has been a feature request for the possibility of grouping analyses per asset (e.g. linking a given analysis to a specific location, project, or platform)

The overview page of Analysis Platform should contain a list of assets (rather than analyses), where a user can list analyses for a given asset.

**API:**
- [x] Add a blueprint `Asset` to [AnalysisPlatformDS/Blueprints](https://github.com/equinor/data-modelling-tool/tree/master/api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints)
  - Suggested fields:
    - [x] Name
    - [x] Description
    - [x] Location
    - [x] Manager / asset responsible?
    - [x] Start & end dates?
    - [x] Creator, createdAt, updatedAt
    - [x] Analysis[] (list of associated analyses)
- [x] Add a blueprint `Location` to [AnalysisPlatformDS/Blueprints](https://github.com/equinor/data-modelling-tool/tree/master/api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints)
  - Suggested fields:
    - Name
    - Latitude
    - Longitude 
- [x] ~Add field, "asset", to the [Analysis blueprint](https://github.com/equinor/data-modelling-tool/blob/master/api/src/home/analysis-platform/data/AnalysisPlatformDS/Blueprints/Analysis.json)~ *Not doing*

**Web:**
- [x] Update dashboard / overview page of AP to list assets rather than analyses (`/ap`)
- [x] Move list of analyses to `/ap/asset/<asset_id>`
- [x] ~Add an "Asset" selector input to "Create analysis" form~ *not doing*
- [x] Add "Create Asset":
  - [x] button
  - [x] form

**Comment by KristianKjerstad** [comment]
good!

here are some other issues we can consider/investigate

- [ ] Should users be allowed access to all assets? Or do we have to implement access control for assets
- [ ] define what user roles that should be allowed to create new asset (related to "Add "Create Asset" button & form")

**Comment by KristianKjerstad** [comment]
i didn't quite understand what "Move list of analyses to /ap/asset/<asset_id>" means

**Comment by soofstad** [comment]
I think the reference should be the other way around. An asset, should point to several analysis.

**Comment by netr0m** [comment]
> I think the reference should be the other way around. An asset, should point to several analysis.

Sort of agree, but the downside there is having to update the asset for every analysis created/deleted, in addition to creating the analysis itself. Beneficial in terms of querying though.

**Comment by netr0m** [comment]
> good!
> 
> here are some other issues we can consider/investigate
> 
> * [ ]  Should users be allowed access to all assets? Or do we have to implement access control for assets
> * [ ]  define what user roles that should be allowed to create new asset (related to "Add "Create Asset" button & form")

Yeah, good points. Should probably discuss this in a meeting, possibly involving Babak? @soofstad @eoaksnes
