### ISSUE TITLE
move plugins to repository called dm-packages

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-tool#1412]
- Also add publish CI (see https://github.com/soofstad/react-oauth2-pkce for inspiration)

**Comment by eoaksnes** [comment]
Alternative options:

1. Many repositories (install from Git URL)
2. Single repository (many tar URLs)
3. Single repository (many NPM packages)

Conclusion: Try out option 2.

**Comment by soofstad** [comment]
done: https://github.com/equinor/dm-core-packages
